### ISSUE TITLE
Implement minimization of clipped convex functions for outlier detection

### ISSUE THREAD

**Issue by angeris** [jbytecode/LinRegOutliers#7] opened 2020-09-22 18:18 UTC
(For original context on this issue, see [here](https://twitter.com/mhsatman/status/1308468760207032327) and thread.)

There are some basic heuristics in [this paper](https://link.springer.com/article/10.1007/s11590-020-01565-4) ([here's](https://arxiv.org/abs/1910.12342) an arXiv PDF with better formatting) for outlier detection and data fitting, when the problem of fitting with outliers is specified as the minimization of a sum of clipped convex functions. The algorithm is relatively short, doesn't really require many parameters, and seems to have good performance in practice, so, if there is any interest, it might be worth including!

CC: @sbarratt

**Comment by jbytecode** [comment] 2020-09-22 18:27
Hi @angeris 

It seems the proposed algorithm behaves like a robust regression estimator, right? If yes, it is proper for the context of the package. 

Your contributions are welcome. Any implemented method in this package takes a RegressionSetting argument which includes a formula and a data object. You can read, for example Hadi & Simonoff (1993), lts, lms or Pena & Yohai (1995), implementations in the package.

Don't hesitate for any help. Please write proper tests and make sure everything is passed. You can start with forking the project and make pull requests. 

Thank you in advance.

**Comment by angeris** [comment] 2020-09-22 18:31
> Hi @angeris
> 
> It seems the proposed algorithm behaves like a robust regression estimator, right? If yes, it is proper for the context of the package.

Indeed! As a side question: we can implement any number of (convex) loss functions with outlier detection. Least-squares is particularly simple and lends itself well to a (very) short algorithm, but more general ones can be considered. I haven't taken a detailed look at the package, but is it worth also implementing other loss functions? (e.g, L1-norm).

> Your contributions are welcome. Any implemented method in this package takes a RegressionSetting argument which includes a formula and a data object. You can read, for example Hadi & Simonoff (1993), lts, lms or Pena & Yohai (1995), implementations in the package.

Sounds great! Will do.

> Don't hesitate for any help. Please write proper tests and make sure everything is passed. You can start with forking the project and make pull requests.

Perfect, thanks :)

> Thank you in advance.

**Comment by jbytecode** [comment] 2020-09-22 18:34
L1-norm is LAD (least absolute deviations regression) and it is implemented in the src/lad.jl.
The trimmed version of this algorithm is also implemeneted (see /src/lta.jl). Their documentation and references stands on the top of their function implementations.

**Comment by jbytecode** [comment] 2020-09-23 05:48
To come your side question, type of loss function may be a function argument or implemented in seperate methods. How things change when the loss function changes? Masking & Swamping rates?

**Comment by angeris** [comment] 2020-09-23 16:28
> How things change when the loss function changes? Masking & Swamping rates?

The heuristic is fairly short/simple; essentially it's a basic form of alternating minimization. (See S3 of [here](https://arxiv.org/pdf/1910.12342.pdf), "Alternating minimization" and "Inexact alternating minimization," pg. 5.) In the L2 case, all of the subproblems have closed-form solutions so implementing it should only be a few lines of code. In the more general case, we have to solve a convex subproblem in one step, which is often pretty efficient (for example, in the L1 case, we can just call LAD directly as part of the subroutine).

Let me know if that answers your question ! :)

**Comment by jbytecode** [comment] 2020-09-23 16:39
Okay, perfect. Thank you in advance.
The loc is not too much important, it will be good to have a novel method like yours. In case of the implementation, having a function or two for both L1 and L2 seems to be enough. Besides the basics, feel free to take responsibility for this algorithm because it is entirely yours.

Waiting for your contributions. 

Best.

**Comment by jbytecode** [comment] 2020-10-06 17:47
Hi @angeris, is there any progress in this matter?

**Comment by angeris** [comment] 2020-10-07 21:28
Apologies! I've been slightly backed up with other research work. Will try and get it by end of week. (cc: @sbarratt)

**Comment by jbytecode** [comment] 2020-10-08 08:17
@angeris no worries, it is good to hear from you. What a good news! Me and @tantei3 recently added some new algorithms and code enhancements and having your valuable algorithm implemented in the package will be awesome enhancement. Thank you.

**Comment by angeris** [comment] 2020-10-13 20:56
Quick question: do any algorithms implement regularization? (Sorry, a quick search doesn't find any, so I don't know what the standard interface would be!)

**Comment by jbytecode** [comment] 2020-10-14 03:41
Hi @angeris, can you please more clear about regularization?

**Comment by angeris** [comment] 2020-10-19 16:10
Sure! So, the usual least-squares problem is
```
minimize ||Xθ - y||²
```
and the clipped version of this problem (as defined in the paper) is
```
minimize ∑ᵢ min{(xᵢ'θ - yᵢ)², a}
```
where a is some real number setting the outlier threshold.

The regularized version of the clipped convex problem simply penalizes the θs giving
```
minimize ∑ᵢ min{(xᵢ'θ - yᵢ)², a} + λ||θ||²
```
where λ ≥ 0 is the regularization strength. This is, of course, similar to the usual regularized least squares problem:
```
minimize ||Xθ - y||² + λ||θ||²
```
except we replace the least squares objective with its clipped version.

**Comment by jbytecode** [comment] 2020-10-19 16:29
Well, I don't think our other algorithms use regularization. As I my understanding, you are unsure on implementing the regularization in a general manner or problem specific. At this point, we can desire implementing specific to your algorithm and If we further need a general regularization, we can separate the implementation. Finally, it is up to you.

**Comment by angeris** [comment] 2020-10-19 16:37
Ok, sounds good! I will not implement it, in order to follow the current implementation of the algorithms. (Though I can implement it later, if we later decide to add it to the other ones, too!)

**Comment by jbytecode** [comment] 2020-10-19 16:39
okay very nice, thank you, go on.

**Comment by jbytecode** [comment] 2020-10-19 19:23
okay @angeris , I added documentation for you.

You are now a part of the LinRegOutliers project with your valuable contributions. Thank you!

I am closing this issue, thank you!

**Closed** 2020-10-19 19:23 UTC
Labels: enhancement
